version: '3.7'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: pycharmer/proeda:latest
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - 8000

  nginx:
    image: nginx:1.19.2
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - 80:80
    depends_on:
      - web